apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-values
  namespace: observability
data:
  values.yaml: |
    loki:
      auth_enabled: false
      storage:
        type: filesystem
      schemaConfig:
        configs:
        - from: 2024-04-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    deploymentMode: SingleBinary
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        size: 10Gi
        storageClass: standard
    gateway:
      enabled: false
    monitoring:
      selfMonitoring:
        enabled: false
        grafanaAgent:
          installOperator: false
