apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-values
  namespace: observability
data:
  values.yaml: |
    prometheus:
      prometheusSpec:
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        retention: 30d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: standard
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
    grafana:
      enabled: true
      service:
        type: NodePort
        nodePort: 30300
      adminPassword: admin123
      persistence:
        enabled: true
        storageClassName: standard
        size: 5Gi
    alertmanager:
      enabled: true
      service:
        type: NodePort
        nodePort: 30900
