apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: default
  labels:
    app: user-service
    service: user-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: user-service
