apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-gateway-values
  namespace: istio-system
data:
  values.yaml: |
    service:
      type: NodePort
      ports:
      - port: 15021
        targetPort: 15021
        name: status-port
        nodePort: 30021
      - port: 80
        targetPort: 8080
        name: http2
        nodePort: 30080
      - port: 443
        targetPort: 8443
        name: https
        nodePort: 30443
