apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: default
  labels:
    app: product-service
    service: product-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: product-service
